"""add table banned

Revision ID: 85231ed48a55
Revises: a56d1d7f1f50
Create Date: 2025-09-28 19:42:53.650036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85231ed48a55'
down_revision: Union[str, None] = 'a56d1d7f1f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('admin_username', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_tg_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_tg_id_key'), 'users', ['tg_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'user_id')
    op.drop_table('banned')
    # ### end Alembic commands ###
